### ISSUE TITLE
I219V驱动不了，试过了IntelMausiEthernet及IntelMausi，请问您是怎么解决的？

### ISSUE THREAD

**Issue by milkai** [geek5nan/Hackintosh-Z270i#2]
相同的硬件，试过了IntelMausiEthernet及IntelMausi，请问您是怎么解决的？

**Comment by geek5nan** [comment]
您好，我的电脑桌附近缺少网口，所以最近几个版本中都只用到了无线网络。
关于有线网络相关的问题，暂时无法给您答复，请见谅。

**Comment by geek5nan** [comment]
![Ethernet](https://user-images.githubusercontent.com/3816374/76429076-7f26cb00-63e9-11ea-9bf3-6cacdcdaf7cb.png)

偏好设置-系统报告-硬件-以太网卡

你可以在这个路径下可以看到如上图所示的信息吗

**Comment by geek5nan** [comment]
另外，以太网卡在其他系统是否正常，BIOS 中的以太网卡是否正确开启？

**Comment by milkai** [comment]
首先表示感谢！
系统报告中无网卡信息，网卡在其他系统中正常使用，BIOS中设置正常。启动参数-v后，能看到[Ethernet]IntelMausi开头的信息，估计已经加载？在hackintool的Installed中未显示IntelMausiEthernet，但是kext wizard中已经能搜索到该kext。有点迷糊了……

**Comment by milkai** [comment]
在Hackintool的PCI硬件列表中能看见i219V2这个设备(0x15B88086)。

**Comment by geek5nan** [comment]
设备 ID 出来了，但硬件没有加载到，有点奇怪。

我的 config 文件中也没什么特殊的设置，但我的系统报告中可以看到，我在之前 10.13~10.14 中插网线是 OK 的。

一时半会儿还真搞不清楚这个问题的具体原因。

**Comment by WenSong-L** [comment]
10.15.5同情况，不过我也在用WIFI。另外会经常画面撕裂`花屏甚至整个卡死，注入显示器信息的方法未解决，是因为没核显？91F+RX570，请指教谢谢🙏

**Comment by peakstar001** [comment]
解决了吗，遇到了同样问题

**Comment by WenSong-L** [comment]
> 解决了吗，遇到了同样问题

刷BIOS有时会丢失网卡MAC地址，在DOS下刷回就可以了。
